repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.5
    hooks:
      - id: ruff
        args: [--fix]
        exclude: ^packages/patera-frontendext/src/patera/frontendext/_static/_main\.py$
      - id: ruff-format
        exclude: ^packages/patera-frontendext/src/patera/frontendext/_static/_main\.py$

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        exclude: ^packages/patera-frontendext/src/patera/frontendext/_static/_main\.py$
      - id: end-of-file-fixer
        exclude: ^packages/patera-frontendext/src/patera/frontendext/_static/_main\.py$
      - id: check-yaml
      - id: check-toml
